const Meat=[{
    id:1,
    name:"猪肉",
    heat:331,//热量(千卡)
    classify:'畜肉类及制品',//分类
    fat:30.1,//脂肪(千卡)
    cellulose:'-',//纤维素(克)
    carbohydrates:'-',//碳水化合物(克)
    protein:15.1,//蛋白质(克)
    vitamin_A:'-'//维生素A(微克)
},{
    id:2,
    name:"猪肉(肥)",
    heat:807,
    classify:'畜肉类及制品',
    fat:88.6,
    cellulose:'-',
    carbohydrates:'-',
    protein:2.4,
    vitamin_A:'-'
},{
    id:3,
    name:"猪肉瘦",
    heat:143,
    classify:'畜肉类及制品',
    fat:6.2,
    cellulose:'-',
    carbohydrates:1.5,
    protein:20.3,
    vitamin_A:'-'
},{
    id:4,
    name:"猪大肠",
    heat:196,
    classify:'畜肉类及制品',
    fat:18.7,
    cellulose:'-',
    carbohydrates:'-',
    protein:6.9,
    vitamin_A:'-'
},{
    id:5,
    name:"猪大排",
    heat:264,
    classify:'畜肉类及制品',
    fat:20.4,
    cellulose:'-',
    carbohydrates:1.7,
    protein:18.3,
    vitamin_A:'-'
},{
    id:6,
    name:"猪耳",
    heat:176,
    classify:'畜肉类及制品',
    fat:11.1,
    cellulose:'-',
    carbohydrates:'-',
    protein:19.1,
    vitamin_A:'-'
},{
    id:7,
    name:"猪蹄",
    heat:260,
    classify:'畜肉类及制品',
    fat:18.8,
    cellulose:'-',
    carbohydrates:'-',
    protein:22.6,
    vitamin_A:'-'
},{
    id:8,
    name:"猪蹄筋",
    heat:156,
    classify:'畜肉类及制品',
    fat:1.4,
    cellulose:'-',
    carbohydrates:0.5,
    protein:35.3,
    vitamin_A:'-'
},{
    id:9,
    name:"猪肚",
    heat:110,
    classify:'畜肉类及制品',
    fat:5.1,
    cellulose:'-',
    carbohydrates:0.7,
    protein:15.2,
    vitamin_A:'-'
},{
    id:10,
    name:"猪脑",
    heat:131,
    classify:'畜肉类及制品',
    fat:9.8,
    cellulose:'-',
    carbohydrates:'-',
    protein:10.8,
    vitamin_A:'-'
},{
    id:11,
    name:"猪血",
    heat:55,
    classify:'畜肉类及制品',
    fat:0.3,
    cellulose:'-',
    carbohydrates:0.9,
    protein:12.2,
    vitamin_A:'-'
},{
    id:12,
    name:"大肉肠",
    heat:273,
    classify:'畜肉类及制品',
    fat:22.9,
    cellulose:'-',
    carbohydrates:4.6,
    protein:12,
    vitamin_A:'-'
},{
    id:13,
    name:"牛肉",
    heat:160,
    classify:'畜肉类及制品',
    fat:8.7,
    cellulose:'-',
    carbohydrates:0.5,
    protein:20,
    vitamin_A:'-'
},{
    id:14,
    name:"牛蹄筋",
    heat:151,
    classify:'畜肉类及制品',
    fat:0.5,
    cellulose:'-',
    carbohydrates:2.6,
    protein:34.1,
    vitamin_A:'-'
},{
    id:15,
    name:"牛鞭",
    heat:117,
    classify:'畜肉类及制品',
    fat:0.7,
    cellulose:'-',
    carbohydrates:'-',
    protein:27.2,
    vitamin_A:'-'
},{
    id:16,
    name:"牛大肠",
    heat:197,
    classify:'畜肉类及制品',
    fat:11.8,
    cellulose:'-',
    carbohydrates:9.6,
    protein:14.9,
    vitamin_A:'-'
},{
    id:17,
    name:"牛肚",
    heat:72,
    classify:'畜肉类及制品',
    fat:1.6,
    cellulose:'-',
    carbohydrates:'-',
    protein:14.5,
    vitamin_A:'-'
},{
    id:18,
    name:"牛脑",
    heat:149,
    classify:'畜肉类及制品',
    fat:11,
    cellulose:'-',
    carbohydrates:0.1,
    protein:12.5,
    vitamin_A:'-'
},{
    id:19,
    name:"牛百叶(黑)",
    heat:70,
    classify:'畜肉类及制品',
    fat:1.9,
    cellulose:'-',
    carbohydrates:'-',
    protein:13.2,
    vitamin_A:'-'
},{
    id:20,
    name:"羊肉",
    heat:139,
    classify:'畜肉类及制品',
    fat:6.5,
    cellulose:'-',
    carbohydrates:1.6,
    protein:18.5,
    vitamin_A:'-'
},{
    id:21,
    name:"羊大肠",
    heat:75,
    classify:'畜肉类及制品',
    fat:2.4,
    cellulose:'-',
    carbohydrates:'-',
    protein:13.4,
    vitamin_A:'-'
},{
    id:22,
    name:"羊脑",
    heat:142,
    classify:'畜肉类及制品',
    fat:10.7,
    cellulose:'-',
    carbohydrates:0.1,
    protein:11.3,
    vitamin_A:'-'
},{
    id:23,
    name:"马肉",
    heat:122,
    classify:'畜肉类及制品',
    fat:4.6,
    cellulose:'-',
    carbohydrates:0.1,
    protein:20.1,
    vitamin_A:'-'
},{
    id:24,
    name:"兔肉",
    heat:102,
    classify:'畜肉类及制品',
    fat:2.2,
    cellulose:'-',
    carbohydrates:0.9,
    protein:19.7,
    vitamin_A:'-'
}]
export default Meat