const Algae=[{
    id:1,
    name:"草菇",
    heat:27,//热量(千卡)
    classify:'algae',//分类
    fat:0.2,//脂肪(千卡)
    cellulose:1.6,//纤维素(克)
    carbohydrates:4.3,//碳水化合物(克)
    protein:2.7,//蛋白质(克)
    vitamin_A:'-'//维生素A(微克)
},{
    id:2,
    name:"大红菇",
    heat:263,
    classify:'algae',
    fat:2.8,
    cellulose:31.6,
    carbohydrates:50.9,
    protein:24.4,
    vitamin_A:'-'
},{
    id:3,
    name:"冬菇",
    heat:277,
    classify:'algae',
    fat:1.3,
    cellulose:32.3,
    carbohydrates:64.6,
    protein:17.8,
    vitamin_A:'-'
},{
    id:4,
    name:"猴头菇",
    heat:21,
    classify:'algae',
    fat:0.2,
    cellulose:4.2,
    carbohydrates:4.9,
    protein:2,
    vitamin_A:'-'
},{
    id:5,
    name:"金针菇",
    heat:32,
    classify:'algae',
    fat:0.4,
    cellulose:2.7,
    carbohydrates:6,
    protein:2.4,
    vitamin_A:'-'
},{
    id:6,
    name:"蘑菇",
    heat:24,
    classify:'algae',
    fat:0.1,
    cellulose:2.1,
    carbohydrates:4.1,
    protein:2.7,
    vitamin_A:'-'
},{
    id:7,
    name:"香菇",
    heat:26,
    classify:'algae',
    fat:0.3,
    cellulose:3.3,
    carbohydrates:5.2,
    protein:2.2,
    vitamin_A:'-'
},{
    id:8,
    name:"平菇",
    heat:24,
    classify:'algae',
    fat:0.3,
    cellulose:2.3,
    carbohydrates:4.6,
    protein:1.9,
    vitamin_A:'-'
},{
    id:9,
    name:"羊肚菌",
    heat:321,
    classify:'algae',
    fat:7.1,
    cellulose:12.9,
    carbohydrates:43.7,
    protein:26.9,
    vitamin_A:'-'
},{
    id:10,
    name:"银耳",
    heat:261,
    classify:'algae',
    fat:1.4,
    cellulose:30.4,
    carbohydrates:67.3,
    protein:10,
    vitamin_A:'-'
},{
    id:11,
    name:"珍珠白蘑",
    heat:258,
    classify:'algae',
    fat:0.7,
    cellulose:23.3,
    carbohydrates:56.3,
    protein:18.3,
    vitamin_A:'-'
},{
    id:12,
    name:"榛蘑",
    heat:177.8,
    classify:'algae',
    fat:3.7,
    cellulose:10.4,
    carbohydrates:31.9,
    protein:9.5,
    vitamin_A:'-'
},{
    id:13,
    name:"茶树菇",
    heat:309,
    classify:'algae',
    fat:2.6,
    cellulose:'-',
    carbohydrates:56.1,
    protein:23.1,
    vitamin_A:'-'
},{
    id:14,
    name:"干巴菌",
    heat:38,
    classify:'algae',
    fat:0.4,
    cellulose:6.3,
    carbohydrates:8,
    protein:3.8,
    vitamin_A:'-'
},{
    id:15,
    name:"黄伞菇",
    heat:294,
    classify:'algae',
    fat:3.2,
    cellulose:'-',
    carbohydrates:57.5,
    protein:22.8,
    vitamin_A:'-'
},{
    id:16,
    name:"杏鲍菇",
    heat:35,
    classify:'algae',
    fat:0.1,
    cellulose:2.1,
    carbohydrates:8.3,
    protein:1.3,
    vitamin_A:'-'
},{
    id:17,
    name:"香杏丁蘑",
    heat:257,
    classify:'algae',
    fat:0.2,
    cellulose:24.9,
    carbohydrates:53.9,
    protein:22.4,
    vitamin_A:'-'
},{
    id:18,
    name:"竹荪",
    heat:248,
    classify:'algae',
    fat:3.1,
    cellulose:46.4,
    carbohydrates:60.3,
    protein:17.8,
    vitamin_A:'-'
},{
    id:19,
    name:"牛肝菌",
    heat:32,
    classify:'algae',
    fat:0.2,
    cellulose:1.6,
    carbohydrates:4.8,
    protein:3.6,
    vitamin_A:'-'
},{
    id:20,
    name:"海带",
    heat:16,
    classify:'algae',
    fat:0.1,
    cellulose:0.9,
    carbohydrates:3,
    protein:1.1,
    vitamin_A:'-'
},{
    id:21,
    name:"发菜",
    heat:259,
    classify:'algae',
    fat:0.5,
    cellulose:35,
    carbohydrates:60.8,
    protein:20.2,
    vitamin_A:'-'
},{
    id:22,
    name:"苔菜",
    heat:167,
    classify:'algae',
    fat:0.4,
    cellulose:9.1,
    carbohydrates:26.3,
    protein:19,
    vitamin_A:'-'
},{
    id:23,
    name:"蛹虫草",
    heat:302,
    classify:'algae',
    fat:'-',
    cellulose:16.3,
    carbohydrates:60.9,
    protein:23.7,
    vitamin_A:'-'
},{
    id:24,
    name:"海冻菜",
    heat:314,
    classify:'algae',
    fat:0.1,
    cellulose:'-',
    carbohydrates:72.9,
    protein:5.4,
    vitamin_A:'-'
}]
export default Algae