const Vegetable=[{
    id:1,
    name:"白萝卜",
    heat:16,//热量(千卡)
    classify:'vegetable',//分类
    fat:0.1,//脂肪(千卡)
    cellulose:'-',//纤维素(克)
    carbohydrates:4,//碳水化合物(克)
    protein:0.7,//蛋白质(克)
    vitamin_A:'-'//维生素A(微克)
},{
    id:2,
    name:"红萝卜",
    heat:22,
    classify:'vegetable',
    fat:0.1,
    cellulose:0.8,
    carbohydrates:4.6,
    protein:1,
    vitamin_A:'-'
},{
    id:3,
    name:"胡萝卜",
    heat:39,
    classify:'vegetable',
    fat:0.2,
    cellulose:1.1,
    carbohydrates:8.8,
    protein:1,
    vitamin_A:'-'
},{
    id:4,
    name:"芥菜头",
    heat:35.8,
    classify:'vegetable',
    fat:0.2,
    cellulose:1.4,
    carbohydrates:7.4,
    protein:1.9,
    vitamin_A:'-'
},{
    id:5,
    name:"甜菜根",
    heat:87,
    classify:'vegetable',
    fat:0.1,
    cellulose:5.9,
    carbohydrates:23.5,
    protein:1,
    vitamin_A:'-'
},{
    id:6,
    name:"紫菜头",
    heat:42,
    classify:'vegetable',
    fat:0.2,
    cellulose:4.2,
    carbohydrates:10.6,
    protein:1.8,
    vitamin_A:'-'
},{
    id:7,
    name:"扁豆",
    heat:41,
    classify:'vegetable',
    fat:0.2,
    cellulose:2.1,
    carbohydrates:8.2,
    protein:2.7,
    vitamin_A:'-'
},{
    id:8,
    name:"豌豆尖",
    heat:225,
    classify:'vegetable',
    fat:'-',
    cellulose:1.3,
    carbohydrates:53.9,
    protein:3.1,
    vitamin_A:'-'
},{
    id:9,
    name:"豆角",
    heat:35,
    classify:'vegetable',
    fat:0.2,
    cellulose:2.6,
    carbohydrates:7.4,
    protein:2.2,
    vitamin_A:'-'
},{
    id:10,
    name:"荷兰豆",
    heat:30,
    classify:'vegetable',
    fat:0.3,
    cellulose:1.4,
    carbohydrates:4.9,
    protein:2.5,
    vitamin_A:'-'
},{
    id:11,
    name:"龙豆",
    heat:36,
    classify:'vegetable',
    fat:0.5,
    cellulose:1.9,
    carbohydrates:5,
    protein:3.7,
    vitamin_A:'-'
},{
    id:12,
    name:"四季豆",
    heat:24,
    classify:'vegetable',
    fat:0.2,
    cellulose:'-',
    carbohydrates:6,
    protein:2,
    vitamin_A:'-'
},{
    id:13,
    name:"辣椒",
    heat:295.4,
    classify:'vegetable',
    fat:12,
    cellulose:41.7,
    carbohydrates:52.7,
    protein:15,
    vitamin_A:'-'
},{
    id:14,
    name:"茄子",
    heat:23,
    classify:'vegetable',
    fat:0.2,
    cellulose:1.3,
    carbohydrates:4.9,
    protein:1.1,
    vitamin_A:'-'
},{
    id:15,
    name:"番茄",
    heat:22,
    classify:'vegetable',
    fat:0.6,
    cellulose:0.8,
    carbohydrates:2.6,
    protein:2,
    vitamin_A:'-'
},{
    id:16,
    name:"秋葵",
    heat:25,
    classify:'vegetable',
    fat:0.2,
    cellulose:1.8,
    carbohydrates:6.2,
    protein:1.8,
    vitamin_A:'-'
},{
    id:17,
    name:"白瓜",
    heat:11.8,
    classify:'vegetable',
    fat:'-',
    cellulose:0.9,
    carbohydrates:2.6,
    protein:0.9,
    vitamin_A:'-'
},{
    id:18,
    name:"南瓜",
    heat:23,
    classify:'vegetable',
    fat:0.1,
    cellulose:0.8,
    carbohydrates:5.3,
    protein:0.7,
    vitamin_A:'-'
},{
    id:19,
    name:"葫芦",
    heat:15.6,
    classify:'vegetable',
    fat:0.1,
    cellulose:0.8,
    carbohydrates:3.5,
    protein:0.7,
    vitamin_A:'-'
},{
    id:20,
    name:"蒜苗",
    heat:40,
    classify:'vegetable',
    fat:0.4,
    cellulose:1.8,
    carbohydrates:8,
    protein:2.12,
    vitamin_A:'-'
},{
    id:21,
    name:"丝瓜",
    heat:20,
    classify:'vegetable',
    fat:0.2,
    cellulose:'-',
    carbohydrates:4,
    protein:1.3,
    vitamin_A:'-'
},{
    id:22,
    name:"蒜黄",
    heat:23.8,
    classify:'vegetable',
    fat:0.2,
    cellulose:1.4,
    carbohydrates:3.8,
    protein:2.5,
    vitamin_A:'-'
},{
    id:23,
    name:"乌菜",
    heat:27.8,
    classify:'vegetable',
    fat:0.4,
    cellulose:1.4,
    carbohydrates:4.2,
    protein:2.6,
    vitamin_A:'-'
},{
    id:24,
    name:"油菜",
    heat:19,
    classify:'vegetable',
    fat:0.2,
    cellulose:0.9,
    carbohydrates:2.9,
    protein:1.8,
    vitamin_A:'-'
}]
export default Vegetable